# Generated by Django 3.2.9 on 2021-12-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='absenceCollection',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='messageCollection',
        ),
        migrations.AddField(
            model_name='absence',
            name='employeeFK',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.employee'),
        ),
    ]
