# Generated by Django 3.2.9 on 2021-11-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
