# Generated by Django 3.2.9 on 2021-11-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_absence_valid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
