# Generated by Django 3.2.9 on 2021-11-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_delete_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='score',
            new_name='monthlyScore',
        ),
    ]
