# Generated by Django 3.2.9 on 2021-11-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0004_rename_score_employee_monthlyscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('WARNING', 'Warning'), ('PROMOTION', 'Promotion'), ('FIRED', 'Fired')], default='WARNING', max_length=9),
        ),
    ]
